name: Run All Test

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main
      - 'releases/**'

jobs:
  run-all-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: List Xcode Versions
        run: ls /Applications | grep Xcode
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
      - name: List SDKs
        run: xcodebuild -showsdks
      - name: Run all tests on iOS
        run: xcodebuild -scheme Vessel -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13 Pro' test
      - name: Run all tests on macOS
        run: xcodebuild -scheme Vessel -sdk macosx12.1 -destination 'platform=macOS' clean test
